### ISSUE TITLE
Differences in performance between version 1.4.7 and 2.0.6

### ISSUE THREAD

**Issue by eloypastor** [opencpu/opencpu#283]
Hello!

I've been experimenting differences in performance in 2 different evironments:

**ENV 1:**
- Ubuntu 14.04
- R 3.1.3 (2015-03-09)
- OpenCPU 1.4.7
- `/etc/opencpu/server.conf`:
```
{
    "enable.api.library": true,
    "enable.api.apps": true,
    "enable.api.bioc": true,
    "enable.api.cran": true,
    "enable.api.gist": true,
    "enable.api.github": true,
    "enable.api.user": true,
    "enable.api.tmp": true,
    "enable.cors" : true,
    "enable.post.code": true,
    "error.showcall": true,
    "gist.cache": 300,
    "github.cache": 86400,
    "cran.cache": 86400,
    "public.url" : "https://public.opencpu.org/ocpu",
    "smtp.server" : "localhost",
    "httpcache.post": 300,
    "httpcache.lib": 86400,
    "httpcache.git": 900,
    "httpcache.gitapi": 120,
    "httpcache.tmp": 86400,
    "httpcache.cran": 86400,
    "httpcache.static": 31536000,
    "httpcache.bioc": 31536000,
    "key.length" : 9,
    "appspaths": "/usr/local/lib/opencpu/apps-library",
    "repos": "http://cran.rstudio.com",
    "rlimit.as": 2e9,
    "rlimit.fsize": 1e8,
    "rlimit.nproc": 50,
    "timelimit.get": 600,
    "timelimit.post": 90,
    "timelimit.webhook": 900,
    "preload": ["ggplot2", "lattice"]
}
```

**ENV 2:**
- Ubuntu 16.06
- R 3.4.3 (2017-11-30)
- OpenCPU 2.0.6
- `/etc/opencpu/server.conf`:
```
{
    "enable.api.library": true,
    "enable.api.apps": true,
    "enable.api.user": true,
    "enable.api.tmp": true,
    "enable.cors" : true,
    "enable.post.code": true,
    "enable.rlimits" : true,
    "error.showcall": true,
    "smtp.server" : "localhost",
    "httpcache.post": 86400,
    "httpcache.lib": 86400,
    "httpcache.apps": 86400,
    "httpcache.tmp": 86400,
    "httpcache.static": 31536000,
    "key.length" : 9,
    "repos": "https://cran.rstudio.com",
    "rlimit.as": 4e9,
    "rlimit.fsize": 1e9,
    "rlimit.nproc": 100,
    "timelimit.get": 60,
    "timelimit.post": 90,
    "timelimit.webhook": 900,
    "preload": ["lattice","ggplot2"]
}
```

I've installed the same package in 2 environmets. The `DESCRIPTION` of the package is:
```
Package: modelosFord
Type: Package
Title: Ejecuta distintos Modelos Econom<c3><a9>tricos
Authors@R: c(person("Pilar Serrano", "Senior Analyst", role = c("aut"),
         email = "pilar.serrano@conento.com"),person("Santiago Valles", "Senior IT Consultant", role = c("cre"),
         email = "pilar.serrano@conento.com") )
Version: 1.0
Date: 2015-03-27
Author: Pilar Serrano [aut], Santiago Valles [cre]
Maintainer: Santiago Valles <santiago.valles@conento.com>
Description: C<c3><a1>lculo de los modelos de Ford
License: Conento
Depends: lubridate
Packaged: 2015-07-22 07:59:05 UTC; santiago.valles
```

When I make HTTP Request to the same method in this 2 environments I get differences in response time about 1 second:

**ENV 1:**
![image](https://user-images.githubusercontent.com/8298906/35044285-13249f36-fb90-11e7-92aa-0c5ab72c5542.png)

**ENV 2:**
![image](https://user-images.githubusercontent.com/8298906/35044324-3c58b734-fb90-11e7-9747-c0861df727e9.png)

As you can see, the **ENV 2** is, at least, 1 second slower than **ENV 1**. Also, in **ENV 2** a function that spends 8 ms in execute in R (measured by `microbenchmark` package) takes between 3-7 seconds when is called by OpenCPU.
What is wrong in **ENV 2**?

Thanks!

**Comment by jeroen** [comment]
That's not expected. Is your machine running out of memory perhaps? Can you try adding your package to preload in server.conf?

**Comment by eloypastor** [comment]
I tried adding the package to preload. The result is the same. I.ve just restarded the server and i hace the same results. The server has 2GB of RAM and is fully dedicated to OpenCPU.

**Comment by eloypastor** [comment]
Sorry, 1GB of RAM

**Comment by jeroen** [comment]
I suspect your machine is running out of RAM. Can you check `top`? Are you running other things on the machine?

**Comment by Andreas-Lehmann** [comment]
We are experiencing a similar issue while migrating from openCPU 1.5.6 to 2.0.6.
We have set up a test scenario using two VMs of the same size (4 vcpus, 8 GB memory) and we see that the same request to the same R package takes about 2 seconds longer on the new version (from 0.549 to 2.505 seconds). In a load test scenario, it is even worse, here we end up with an increased average response time from 2.31 to 16.0 seconds.

**Env 1**
- Ubuntu 14.04 LTS
- R 3.2.5 (2016-04-14)
- OpenCPU 1.5.6

**Env 2**
- Ubuntu 16.04 LTS
- R 3.4.3 (2017-11-30)
- OpenCPU 2.0.6

Both virtual machines are clean setup running only OpenCPU and some basic Linux maintenance tasks. The memory consumption during the load test was on both VMs nearly 40% and around 10% in idle mode.

@eloypastor have you already found any solution for this?

I will post an update if we get any new insights into this issue...

**Comment by jeroen** [comment]
Hmm that certainly should not happen. Do you have any details about the package you are loading? Do you have many dependencies? Are those preloaded in `/etc/opencpu/server.conf`?

**Comment by Andreas-Lehmann** [comment]
Hey, yes we preload some packages. But we use a custom configuration like`/etc/opencpu/server.conf.d/custom.conf`.

We use a set of three custom build R packages with the following dependencies:
**DESCRIPTION (Package A)**
```
Package: packageA
...
LazyData: true
RoxygenNote: 5.0.1
Depends: R (>= 3.2.5)
Imports: lubridate, packageC, jsonlite,
        packageB(>= 0.1.2)
Suggests: testthat
NeedsCompilation: no
```

**DESCRIPTION (Package B)**
```
Package: packageB
...
LazyData: true
RoxygenNote: 5.0.1
Depends: R (>= 3.2.5)
Imports: lubridate, packageC, jsonlite
Suggests: testthat
NeedsCompilation: no
```

**DESCRIPTION (Package C)**
```
Package: packageC
...
Depends: R (>= 3.2.5)
Imports: lubridate, roxygen2, RODBC, jsonlite, RCurl, digest, XML,
        devtools (>= 1.11.1)
RoxygenNote: 6.0.1
Suggests: testthat
NeedsCompilation: no
```

In our `custom.conf`` we preload:
```
  "Preload": [
    "packageC",
    "packageA"
  ]
```

This seemed to work fine with the 1.5.6 version of OpenCPU.

Do you recommend to preload all depended packages as well?

**Comment by jeroen** [comment]
> Do you recommend to preload all imported packages as well?

It should be needed but can you try at least to see if this is the problem? Recent versions of R have switched to lazy loading dependencies, so it may be that they no longer automatically get preloaded if they are not explicitly imported in your NAMESPACE file.

Also you can try adding some "warmup" code to the file `/etc/opencpu/Rprofile`. This code will be executed in each when the server starts. Try loading packages or data here, see if that helps.

**Comment by Andreas-Lehmann** [comment]
Thanks for your support.
I have added all packages to preload:
`"preload": ["RODBC", "roxygen2", "RCurl", "digest", "XML", "lubridate", "jsonlite", "packageC", "packageB", "packageA"]` this improved the speed, but still not at the level of the old version.

Now we are at 1.154 seconds for a single request and an average of 4.33 seconds in a load scenario.

|| single request | load scenario |
|--|--|--|
| OpenCPU 1.5.6 | 0.549 | 2.31 |
| OpenCPU 2.0.6 | 2.505 | 16.0 |
| OpenCPU 2.0.6 *(full preload)* | 1.154 | 4.33 |

All required packages are explicitly imported in the NAMESPACE file in each of our packages, we do not import sub-dependencies of referenced packages, this shall be handled by R.

I will try to play around with some "warmup" code to see if that helps.

**Comment by Andreas-Lehmann** [comment]
I don't know if this is related to the problem but I noticed that the old OpenCPU version returns a `HTTP 200 OK` while the new one returns a `HTTP 201 Created` (as shown on the screenshot below).
![image](https://user-images.githubusercontent.com/28807194/35863170-1d8c8c5e-0b4e-11e8-9dc2-9615d9fb8810.png)

**Comment by jeroen** [comment]
Is your function returning lage amounts of data? IIRC we switched to saving some additional response data, but the differences should be marginal.

**Comment by Andreas-Lehmann** [comment]
No there is no large amounts of data, response is much smaller than request:
Bytes Request:		4.036		(headers: 626; body: 3.410)
Bytes Response:	974		(headers: 825; body: 149)

**Comment by jeroen** [comment]
Then there should be no more than a few sec overhead in calling the function through opencpu or via R.

Are you running the latest build of opencpu-server? Try `apt-get dist-upgrade` just in case.

Are your functions loading any datasets or so? Any luck adding some warmup calls to the profile? Does the time go down after you have made a few requests to the server or does it stay this high?

**Comment by Andreas-Lehmann** [comment]
We are running OpenCPU version 2.0.6 (shall be the latest right?).
Preloading packages in warmup calls does not speed up things in our case, there was a slight performance decrease compared to the complete preload per `server.conf`.

Our load test scenario simulates a constant load of 20 parallel requests for 5 minutes.
Here is the graph for the 2.0.6 version:
![image](https://user-images.githubusercontent.com/28807194/35867166-6bcecf5c-0b59-11e8-99d4-9ab4bd11ffba.png)

compared to the 1.5.6 version:
![image](https://user-images.githubusercontent.com/28807194/35867263-a8c2dbec-0b59-11e8-92e3-fa64f37a7e87.png)

In both cases there is a peak at the beginning of the test until it stays on the same level. As you see, the peak of the new version is around 10 seconds max. while the peak of the old version is only around 4 seconds.

Currently we try to measure the raw R performance with adding some tracing to our packages to see if the code is running slower or if there is any calling or response overhead.

I will post an update when we have any new results.

**Comment by jeroen** [comment]
That's very interesting. Does the same happen when you do less concurrent requests? Can you verify that the apache2 __prefork mpm__ is enabled?

```
sudo apachectl -V | grep MPM
```

Perhaps apache does not have enough workers available and therefore requests get queue'd. Try tweaking apache config and raising these:

 - [`MaxRequestWorkers`](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxrequestworkers)
 - [`ServerLimit`](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#serverlimit)
 - [`StartServers`](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#startservers)
 - [`MaxSpareServers`](https://httpd.apache.org/docs/2.4/mod/prefork.html)

I think you need to tweak these in either `/etc/apache2/sites-enabled/opencpu.conf` or globally in `/etc/apache2/mods-enabled/mpm_prefork.conf`.

**Comment by eloypastor** [comment]
Hi @Andreas-Lehmann! I haven't found a solution yet. I'll try @jeroen's recomendations and i'll post the results

**Comment by zerweck** [comment]
> I think you need to tweak these in either /etc/apache2/sites-enabled/opencpu.conf or globally in /etc/apache2/mods-enabled/mpm_prefork.conf.

How would setting these be related to the `rlimit.nproc` setting in a `/etc/opencpu/server.conf.d/.*conf` file?

**Comment by Andreas-Lehmann** [comment]
We now have the result of the R runtime measurement.
The following table shows the R code execution time in milliseconds measured during a 5 -minute load test.

| | OpenCPU 1.5.6 | OpenCPU 2.0.6 |
|---|---|---|
| max | 1.713 | 3.836 |
| min | 102 | 431 |
| avg | 432 | 2.144 |

So it seems that most of the additional time is consumed during the code execution. We now try to find a good test setup to separate the impact of the updated R runtime. Therefore, we will try to run a similar test outside of an OpenCPU environment on the same virtual machine size, but this will need some time to prepare.
I will post an update once we have new results...

**Comment by jeroen** [comment]
OK lmk if I can help. If there is any code you can share, I can try to debug on my end what the overhead seems to be. Also if your code is open you use the public cloud server to see if there is an hw issue.

**Comment by Andreas-Lehmann** [comment]
We have done some further investigations and run our R code in a local R session. Therefore, I wrapped the R call in a loop with 1.000 iterations and run this on both virtual machines in a SSH session.

| | R 3.2.5 *(oCPU 1.5.6)* | R 3.4.3 *(oCPU 2.0.6)* |
|---|---|---|
| max | 3.678 | 382 |
| min | 135 | 66 |
| avg | 410 | 81 |

We used the same measurements as in the comment above (R execution time in milliseconds), but we see a significant difference in the runtime of the newer R version while the runtime in the old version is nearly the same as in OpenCPU.

**Comment by jeroen** [comment]
> We used the same measurements as in the comment above (R execution time in milliseconds), but we see a significant difference in the runtime of the newer R version while the runtime in the old version is nearly the same as in OpenCPU.

What exactly do you mean? That the performance between vanilla R and opencpu is comparable in the old 1.5.6 server, but not on the new 2.0.6server?

**Comment by Andreas-Lehmann** [comment]
> What exactly do you mean? That the performance between vanilla R and opencpu is comparable in the old 1.5.6 server, but not on the new 2.0.6server?

At least it seems so, we run the test on the same VMs where OpenCPU is installed. We just used a new R session on the console to execute the code.

In OpenCPU we use `POST` `../library/packageA/R/api_function/json` with corresponding parameters. On the console I used:
```R
library(jsonlite)
library(packageA)

# convert request JSON strings to R objects
paramA <- fromJSON("{...}")
paramB <- fromJSON("{...}")
paramC <- fromJSON("{...}")

for (i in 1:1000) {
  result <- api_function(paramA , paramB , paramC )
  print(i)
}
```

The measurement happens inside the `api_function` it takes the time between entering the function and before returning the result.

**Comment by jeroen** [comment]
And this happens happens also if you don't have many concurrent requests? I don't understand it, I run the standard configuration on the public server and there is basically zero overhead.

Can you try to setting `rlimit.nproc : null` in `/etc/opencpu/server.conf` and then `sudo apachectl restart`?

**Comment by Andreas-Lehmann** [comment]
I have modified the load test to use only one concurrent user and let it run for 1000 calls.
The result (OpenCPU call duration in seconds) is:

| | R 3.2.5 *(oCPU 1.5.6)* | R 3.4.3 *(oCPU 2.0.6)* |
|---|---|---|
| max | 0.79 | 0.93 |
| min | 0.46 | 0.78 |
| avg | 0.52 | 0.82 |
| total duration | 08:45 | 13:53 |

Still we are slower with the new version.
The `rlimit.nproc` on both VMs is currently set to `1000` in our `custom.conf`.
I can try to set it to `null`, but I don't think we reached that limit in the single concurrency test.

**Comment by jeroen** [comment]
OK so for single requests the difference seems much smaller (0.3 sec on average). So this indicates part of the problem is the concurrency handing.

Did you have a chance to tweak the apache prefork settings as I [suggested above](https://github.com/opencpu/opencpu/issues/283#issuecomment-363466440)? It could be that apache is simply not using enough workers.

I suggested disabling rlimits because some virtualization systems (in particular container solutions) have bugs, or at least very unexpected interpretation of these limits.

**Comment by jeroen** [comment]
Hi @Andreas-Lehmann I have released a new version opencpu 2.0.7 which fixes a performance bug in the serialization code. Could you maybe test if this makes any difference?

**Comment by Andreas-Lehmann** [comment]
Hi @jeroen I had not much time for investigation the last weeks, but still on it. I will try out the new version later this week and let you know the result.

Thanks again for your support on this.

**Comment by Andreas-Lehmann** [comment]
I have setup a new VM (same size as before) and installed OpenCPU 2.0.7 on it. Then I run the same test (1000 calls) and the result is:

| | R 3.4.3 (oCPU 2.0.7) |
| -- | -- |
| max | 0.75 |
| min | 0.64 |
| avg | 0.68 |
| total duration | 11:27 |

So yes, I can confirm a performance improvement compared to the 2.0.6 version.

**Comment by jeroen** [comment]
Hmm what about the heavy load scenenario? Because that was the biggest regression right?

**Comment by Andreas-Lehmann** [comment]
In our load test scenario (5 minutes of 20 concurrent requests) we have the following result:

| | R 3.2.5 (oCPU 1.5.6) | R 3.4.3 (oCPU 2.0.7) |
| -- | -- | -- |
| max¹ | 3.84 | 10.7 |
| min¹ | 2.38 | 2.57 |
| avg¹ | 2.55 | 5.01 |
| total calls² | 2328 | 1181 |

*¹ in seconds*
*² within 5 minutes*

There we still experience a large performance decrease.
